import {spawnSync} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
function probeBin(names){for(const n of names){const v=spawnSync(n,['--version'],{encoding:'utf8'});if(v.status===0){const h=spawnSync(n,['--help'],{encoding:'utf8'});return {binary:n,version:(v.stdout||v.stderr||'').trim(),help:(h.stdout||h.stderr||'')}}}return null;}
export function probe(host){if(host==='claude')return probeBin([process.env.AI_SDLC_CLAUDE_BIN,'claude'].filter(Boolean));if(host==='codex')return probeBin([process.env.AI_SDLC_CODEX_BIN,'codex'].filter(Boolean));if(host==='antigravity')return probeBin([process.env.AI_SDLC_ANTIGRAVITY_BIN,'agy','antigravity'].filter(Boolean));throw new Error('unknown host');}
export function capabilities(host,p){const h=p?.help||'';return {host,available:!!p,version:p?.version||null,structured_output:/json-schema|output-schema|json schema/i.test(h),resumable:/resume|continue|previous/i.test(h),sandbox:/sandbox|permission-mode/i.test(h),mcp:/mcp/i.test(h)};}
function sandboxForStage(stage){return ['IMPLEMENT','VERIFY'].includes(stage)?'workspace-write':'read-only';}
export function buildInvocation(host,prompt,schemaPath,budget={}){const p=probe(host);if(!p)return {status:'PENDING',reason:'HOST_CLI_NOT_FOUND',argv:null};const h=p.help||'';if(host==='claude'){const a=[p.binary,'-p',prompt,'--output-format','json'];if(/--max-turns/.test(h)&&budget.maxTurns)a.push('--max-turns',String(budget.maxTurns));if(/--json-schema/.test(h)&&schemaPath)a.push('--json-schema',schemaPath);return {status:'READY',argv:a,version:p.version};}
 if(host==='codex'){const a=[p.binary,'exec','--json'];if(/--ephemeral/.test(h))a.push('--ephemeral');if(/--sandbox/.test(h))a.push('--sandbox',sandboxForStage(budget.stage));if(/--output-schema/.test(h)&&schemaPath)a.push('--output-schema',schemaPath);a.push(prompt);return {status:'READY',argv:a,version:p.version};}
 const a=[p.binary];if(/--print/.test(h))a.push('--print',prompt);else a.push(prompt);if(/--output-format/.test(h))a.push('--output-format','json');if(/--json-schema/.test(h)&&schemaPath)a.push('--json-schema',schemaPath);if(/--sandbox/.test(h))a.push('--sandbox');return {status:'READY',argv:a,version:p.version};}
export function runHost(host,prompt,schemaPath,budget={}){const inv=buildInvocation(host,prompt,schemaPath,budget);if(inv.status!=='READY')return inv;const r=spawnSync(inv.argv[0],inv.argv.slice(1),{encoding:'utf8',timeout:budget.maxWallMs||900000,maxBuffer:20*1024*1024});return {...inv,exit_code:r.status??1,stdout:r.stdout||'',stderr:r.stderr||'',status:r.status===0?'PASS':'FAIL'};}
