#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {ROOT,VERSION,HOSTS,packageDigest,corpusDigest,qualificationSubjectDigest,freshEnough,utcNow,exitCode} from './qualification-lib.mjs';
const argv=process.argv.slice(2);const vals=k=>argv.flatMap((x,i)=>x===k&&argv[i+1]?[argv[i+1]]:[]);const val=k=>{const a=vals(k);return a.at(-1)||null;};
const specs=vals('--evidence');const output=val('--output')||path.join(ROOT,'dist','LIVE-QUALIFICATION-RESULT.json');const approval=val('--approval')||path.join(ROOT,'dist','V3-PROMOTION-APPROVAL.json');
const files={};for(const s of specs){const i=s.indexOf('=');if(i<1){console.error(`invalid --evidence ${s}; expected HOST=PATH`);process.exit(1);}files[s.slice(0,i)]=s.slice(i+1);}
if(!specs.length){for(const h of HOSTS){const p=path.join(ROOT,'evals','qualification',`${h}-full-v${VERSION}.json`);if(fs.existsSync(p))files[h]=p;}}
const errors=[],hosts={};const corpus=corpusDigest(),subject=qualificationSubjectDigest();
for(const h of HOSTS){const p=files[h];if(!p){hosts[h]={status:'MISSING',errors:['evidence missing']};continue;}let e;try{e=JSON.parse(fs.readFileSync(p,'utf8'));}catch(err){errors.push(`${h}: invalid JSON ${err.message}`);hosts[h]={status:'INVALID',errors:[err.message]};continue;}const he=[];if(e.schema!=='agent-sdlc/live-host-qualification/v1')he.push('schema mismatch');if(e.version!==VERSION)he.push(`version ${e.version} != ${VERSION}`);if(e.host!==h)he.push(`host ${e.host} != ${h}`);if(e.tier!=='FULL')he.push('tier is not FULL');const fr=freshEnough(e.evaluated_at);if(!fr.valid)he.push(`freshness ${fr.reason}`);if(e.package?.sha256!==packageDigest(h))he.push('package digest mismatch');if(e.package?.verified!==true)he.push('package not verified');if(e.bound_inputs?.corpus_sha256!==corpus)he.push('corpus digest mismatch');if(e.bound_inputs?.qualification_subject_sha256!==subject)he.push('qualification subject digest mismatch');if(e.status==='QUALIFIED'){if(e.promotion_evidence!==true)he.push('promotion_evidence false');if((e.semantic_summary?.PASS||0)!==e.required_semantic_case_count)he.push('semantic PASS count incomplete');if((e.repository_e2e_summary?.PASS||0)!==e.required_repository_e2e_count)he.push('repository E2E PASS count incomplete');}if(he.length)errors.push(...he.map(x=>`${h}: ${x}`));const evStatus=he.length?'INVALID':(['QUALIFIED','PENDING','BLOCKED','FAIL'].includes(e.status)?e.status:'INVALID');if(evStatus==='INVALID'&&!he.length)errors.push(`${h}: unknown evidence status ${e.status}`);hosts[h]={status:evStatus,evidence_file:p,evaluated_at:e.evaluated_at,package_sha256:e.package?.sha256,host_version:e.preflight?.host_version||null,token_usage:e.token_usage||null,errors:he};}
const allQualified=errors.length===0&&HOSTS.every(h=>hosts[h]?.status==='QUALIFIED');const statuses=Object.values(hosts).map(x=>x.status);let status=allQualified?'QUALIFIED_FOR_RC_PROMOTION':statuses.some(x=>x==='INVALID'||x==='FAIL')?'LIVE_QUALIFICATION_FAILED':statuses.some(x=>x==='BLOCKED')?'LIVE_QUALIFICATION_BLOCKED':'LIVE_HOST_PENDING';
const result={schema:'agent-sdlc/release-qualification-result/v1',version:VERSION,evaluated_at:utcNow(),status,promotion_to_rc_allowed:allQualified,required_hosts:HOSTS,bound_inputs:{corpus_sha256:corpus,qualification_subject_sha256:subject},hosts,errors};fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(result,null,2)+'\n');if(allQualified){const app={schema:'agent-sdlc/promotion-approval/v1',from_version:VERSION,target_version:'3.0.0-rc1',approved_at:utcNow(),qualification_result:path.basename(output),qualification_subject_sha256:subject,host_package_sha256:Object.fromEntries(HOSTS.map(h=>[h,packageDigest(h)]))};fs.writeFileSync(approval,JSON.stringify(app,null,2)+'\n');}else fs.rmSync(approval,{force:true});console.log(JSON.stringify(result,null,2));process.exit(allQualified?0:(statuses.some(x=>x==='INVALID'||x==='FAIL')?1:statuses.some(x=>x==='BLOCKED')?3:2));
